//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conector
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public long CARNET { get; set; }
        public string CLAVE { get; set; }
        public int ROL { get; set; }
        public string PREGUNTA { get; set; }
        public string RESPUESTA { get; set; }
    }
}
